spring:
  datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://127.0.0.1:3306/dd
     username: root
     password: root
 
  jpa:
   
    hibernate:
      ddl-auto: update
    show-sql: true
    
  mvc:
       date-format: yyyy-MM-dd
  
 
server: 
      port: 8090
